name: Prep Codespaces

on:
  #push:
  #  branches: [ main ]
  workflow_run:
    workflows: ["CodeQL Scan & Jekyll Deployment"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: prebuild --all
